"""
Alexandria Storage Schemas

Defines the Pydantic models for our LanceDB vector database.
Combines Graph RAG entity relations with the structural metadata 
extracted by the local RoutingChunker pipeline.
"""

from typing import List, Optional
from pydantic import BaseModel, Field
from lancedb.pydantic import LanceModel, Vector

class EntityRelation(BaseModel):
    """Represents a structured multi-hop relation graph edge."""
    source: str = Field(..., description="The originating entity node name.")
    target: str = Field(..., description="The terminating target entity node name.")
    relation: str = Field(..., description="The semantic edge relationship type (e.g., works_with, impacts).")

class ContentChunkMetadata(BaseModel):
    """Vitals tracking array for content ingestion tracking and structural routing."""
    # --- Original Web/General Fields ---
    url: Optional[str] = Field(None, description="Source URL mapping origin.")
    domain: Optional[str] = Field(None, description="Extracted authority domain.")
    timestamp_epoch: Optional[int] = Field(None, description="Unix timestamp of acquisition sequence.")
    lexical_density_score: Optional[float] = Field(None, description="Heuristic semantic text profiling metric.")
    topic_cluster: Optional[str] = Field(None, description="Dynamically assigned thematic data bucket.")
    
    # --- New Local File & Chunker Fields ---
    file_path: str = Field(..., description="Local system path to the ingested file.")
    chunk_type: str = Field(..., description="Routing type: 'code_ast', 'markdown_section', or 'fallback_character'.")
    
    # AST Specific
    node_type: Optional[str] = Field(None, description="AST node classification (e.g., 'function_definition').")
    start_line: Optional[int] = Field(None, description="Starting line in the source code.")
    end_line: Optional[int] = Field(None, description="Ending line in the source code.")
    language: Optional[str] = Field(None, description="Programming language identifier.")
    
    # Markdown Specific
    header: Optional[str] = Field(None, description="Markdown header contextualizing this chunk.")

class IngestionDocumentRecord(LanceModel):
    """
    The master LanceDB record schema reflecting the high-fidelity hybrid storage architecture.
    Inherits from LanceModel to natively support LanceDB vector storage.
    """
    chunk_id: str = Field(..., description="Deterministic cryptographic primary key string.")
    text: str = Field(..., description="Cleaned document string sequence.")
    
    # Vector dimensionality matched to BAAI/bge-small-en-v1.5 (384 dimensions)
    vector: Vector(768) = Field(..., description="Dense numerical embedding generated by local model.")
    
    metadata: ContentChunkMetadata = Field(..., description="Deep structural analytics payload object.")
    relations: List[EntityRelation] = Field(default_factory=list, description="Extracted entity triples tied to this chunk.")
